server:
  port: 9090

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electronic_store
    username: root
    password: Kalamdane@7682
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # File Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Path Configuration
user:
  profile:
    image:
      path: images/users/
